/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Kenko_Art (https://sketchfab.com/kenko_art)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/bought-bread-f7848ac0804d461f9493a87b412bc011
title: Bought Bread
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/scene.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.5}>
          <group position={[-0.71, 0.11, 0]} rotation={[-0.09, -0.27, -0.31]}>
            <mesh
              geometry={nodes.Bag_low_lambert1_0.geometry}
              material={materials.lambert1}
            />
          </group>
          <group position={[-0.71, 0.11, 0]} rotation={[-0.09, -0.27, -0.31]}>
            <mesh
              geometry={nodes.Bread1_low_lambert1_0.geometry}
              material={materials.lambert1}
            />
          </group>
          <group
            position={[-0.87, 0.16, 0.03]}
            rotation={[-0.09, -0.27, -0.31]}
            scale={0.98}
          >
            <mesh
              geometry={nodes.Bread2_low_lambert1_0.geometry}
              material={materials.lambert1}
            />
          </group>
          <group position={[-0.71, 0.11, 0]} rotation={[-0.09, -0.27, -0.31]}>
            <mesh
              geometry={nodes.Bread3_low_lambert1_0.geometry}
              material={materials.lambert1}
            />
          </group>
          <group
            position={[-0.72, 0.11, 0.04]}
            rotation={[-0.09, -0.27, -0.31]}
          >
            <mesh
              geometry={nodes.Bread4_low_lambert1_0.geometry}
              material={materials.lambert1}
            />
          </group>
          <group position={[-0.71, 0.11, 0]} rotation={[-0.09, -0.27, -0.31]}>
            <mesh
              geometry={nodes.Bread5_low_lambert1_0.geometry}
              material={materials.lambert1}
            />
          </group>
          <group position={[-0.71, 0.11, 0]} rotation={[-0.09, -0.27, -0.31]}>
            <mesh
              geometry={nodes.Bread6_low_lambert1_0.geometry}
              material={materials.lambert1}
            />
          </group>
          <group
            position={[-0.09, 2.18, -0.73]}
            rotation={[-0.09, -0.27, -0.31]}
            scale={[5.55, 4.35, 3.49]}
          >
            <mesh
              geometry={nodes.pCube2_lambert2_0.geometry}
              material={materials.lambert2}
            />
          </group>
          <group
            position={[1.77, 3.16, -1.03]}
            rotation={[-0.54, -0.29, -0.57]}
            scale={[1.06, 3.1, 1.06]}
          >
            <mesh
              geometry={nodes.pPlatonic14_lambert2_0.geometry}
              material={materials.lambert2}
            />
          </group>
          <group
            position={[0.21, 2.48, -1.03]}
            rotation={[-0.43, -0.19, -0.33]}
            scale={[1.14, 3.15, 1.14]}
          >
            <mesh
              geometry={nodes.pPlatonic13_lambert2_0.geometry}
              material={materials.lambert2}
            />
          </group>
          <group
            position={[-0.87, 3.68, -1.73]}
            rotation={[-0.28, -0.23, -0.23]}
            scale={[1.11, 3.26, 1.11]}
          >
            <mesh
              geometry={nodes.pPlatonic12_lambert2_0.geometry}
              material={materials.lambert2}
            />
          </group>
          <group
            position={[1.05, 1.9, 0.38]}
            rotation={[0.02, -0.32, -0.5]}
            scale={[0.93, 2.74, 0.93]}
          >
            <mesh
              geometry={nodes.pPlatonic11_lambert2_0.geometry}
              material={materials.lambert2}
            />
          </group>
          <group
            position={[-1.44, 2.67, -0.42]}
            rotation={[0.02, -0.32, -0.09]}
            scale={[0.96, 2.74, 0.96]}
          >
            <mesh
              geometry={nodes.pPlatonic10_lambert2_0.geometry}
              material={materials.lambert2}
            />
          </group>
          <group
            position={[0.53, 3.99, -0.14]}
            rotation={[-0.18, -0.25, -0.5]}
            scale={[1.12, 3.26, 1.12]}
          >
            <mesh
              geometry={nodes.pPlatonic9_lambert2_0.geometry}
              material={materials.lambert2}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/scene.glb");
